### ISSUE TITLE
Allow Booleans to be parsed from languages other than English

### ISSUE THREAD

**Issue by LeopoldArkham** [LeopoldArkham/humanize_rs#3]
## Allow booleans to be parsed from languages other than English

It would be nice to allow for Boolean parsing from other languages.

This could be done several ways:

- Add `to_bool_with_language(maps_to_true, maps_to_false)` that takes two user defined arrays describing what's true and what's false. Meh.

- Add `to_bool_with_language(lang_tag)` that takes a language tag and parses accordingly. Nicer, but makes it hard to allow multiple languages at a time.

- Add a global switch that enables/disables languages. The `to_bool` function interacts with this behind the scenes to parse accordingly.
e.g.
```
    Humanize::enable_lang("English");
    Humanize::enable_lang("Spanish");

    "yes".to_bool(); // Works
    "si".to_bool() // Works too
```
   I think I like this the most.

Pick one of the strategies and implement it.

**Comment by babariviere** [comment]
I think the 3rd is the best but we need to create a global variable to handle enabled language. Do you think it's a good idea to put translation in a file and read them with macro to have a clean code?

**Comment by LeopoldArkham** [comment]
Yes, we probably need to create a `static mut` variable capable of holding the list of languages to be used, and use that in `to_bool` to determine where to go look.

For now I think we can keep the language maps in the code, perhaps in their own file for clarity? We can move them to actual separate files later if needed, it's just not high priority.

Now the question is: How many languages do you speak? :p 

Nice to have you on board.

**Comment by babariviere** [comment]
I speak French, English and Spanish. We can just use a `static` with type `Arc<Mutex<T>>`, this will be safer 😄

**Comment by LeopoldArkham** [comment]
Indeed. Depending on `T` the lazy_static crate might be relevant.

Well those are the same I speak so at least they'll be taken care of. We can ask a shoutout in the next TWIR for people to add their own languages once we have it working.

**Comment by babariviere** [comment]
... or we can use Google Translate 😆

**Comment by LeopoldArkham** [comment]
Yeah that'll get us most of the way. It'll just leave out some of the more idiomatic expressions, if any, but that's far from crucial

**Comment by LeopoldArkham** [comment]
And done.
